# configs/benchmark.yaml
device: "cuda"
seed: 5692
#snr_dbs: [40]
snr_dbs: [0,5,10,15,20,25,30,35,40]
N: 2500 #Number of observations of CTF
L: 1000 #Length of cable for simple model
Zs: 50 #Source impedance = 50 ohms
freq:
  #start_hz: 150000        # 150khz
  #stop_hz: 500000         # 500khz
  start_hz: 2000000      # 2e6
  stop_hz: 10000000      # 10e6
  num_points: 200

target: "ALL3SP" #ALL3sameparams (ALL3SP), ALL3diffparams (ALL3DP)
#ALL3SP means that the same triplet (ZF, ZL, L1) are used to generate all observations. Only difference is the Gaussian noise added to each. (Frequentist)
#ALL3DP means that different triplets (ZF, ZL, L1) are used to generate all observations. Gaussian noise is still added to each. (Bayesian) 

fixed: 
  L1: 250.0
  ZF: {re: 100.0, im: -50.0}
  ZL: {re: 100.0,  im: -5.0}

#Parameter Ranges
true_range:
  L1: {min: 1.0, max: 999.0}  #should always be L - 1 for max        
  ZF:
    re: {min: 1.0, max: 4000.0}
    im: {min: -100.0, max: 100.0}
  ZL:
    re: {min: 1.0, max: 400.0}
    im: {min: -100.0, max: 100.0}
    
# USED ONLY FOR 1D MLE grid search and ELBO-argmax μ grid search
grid:
  L1: {min: 1.0, max: 1000.0, num: 1000}
  ZF:
    re: {min: 1.0, max: 10000.0, num: 1000}
    im: {min: -10000.0, max: 10000.0, num: 1000}
  ZL:
    re: {min: 1.0, max: 10000.0,  num: 1000}
    im: {min: -10000.0, max: 10000.0,  num: 1000}


# --- VI (ELBO-argmax μ) config ---
vi_elbo1d:
  mu_grid: {min: -6.0, max: 6.0, num: 500}
  fixed_sigma: 0.02
  M: 200     # MC samples for ELBO
  K: 100    # MC samples for posterior mean
  sigma_schedule:
    sigma_max: 0.05
    sigma_min: 0.002
    alpha: 1.0
    ref_db: 0.0